[package]
name = "rc5-original-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rc5-core = {workspace = true}
typenum = {workspace = true}
